version: 2

shared: &shared
  working_directory: ~/repo
  environment:
    BOOT_JVM_OPTIONS: -Xmx3200m
  steps:
    - checkout
    - run: apk add curl bash
    - run: .circleci/install_boot.sh
    - run: BOOT_AS_ROOT=yes ./boot testing
    - run: BOOT_AS_ROOT=yes ./boot test

jobs:
  zulu8:
    <<: *shared
    docker:
      - image: azul/zulu-openjdk-alpine:8
  zulu8_clojure1.8:
    <<: *shared
    docker:
      - image: azul/zulu-openjdk-alpine:8
    environment:
      BOOT_CLOJURE_VERSION: 1.8.0
  zulu7:
    <<: *shared
    docker:
      - image: azul/zulu-openjdk-alpine:7
  # "zulu9":
  #   docker:
  #     - image: debian/jessie-minimal
  #   working_directory: ~/repo
  #   environment:
  #     JVM_OPTS: -Xmx3200m
  #     BOOT_JAVA_COMMAND:
  #   steps:
  #     - checkout
  #     - run: .circleci/install_zulu9
  #     - run: .circleci/install_boot.sh
  #     - run: ./boot testing
  #     - run: ./boot test
  # docs:
  #   docker:
  #     - image: azul/zulu-openjdk-8
  #   steps:
  #     - checkout
  #     - run: .circleci/install_boot.sh
  #     - run: ./boot testing
  #     - run: ./boot codox

workflows:
  version: 2
  build:
    jobs:
      - zulu8
      - zulu8_clojure1.8
      - zulu7
      # - docs:
      #   requires:
      #     - zulu8
      #     - zulu8_clojure1.8
      #     - zulu7
    
