version: 2

shared: &shared
  working_directory: ~/repo
  steps:
    - checkout
    - run: apk add curl bash
    - run: .circleci/install_boot.sh
    - run: BOOT_JVM_OPTIONS=-Xmx3200m BOOT_AS_ROOT=yes ./boot testing
    - run: BOOT_JVM_OPTIONS=-Xmx3200m BOOT_AS_ROOT=yes ./boot test

jobs:
  zulu8:
    <<: *shared
    docker:
      - image: azul/zulu-openjdk-alpine:8
  zulu8_clojure1.8:
    <<: *shared
    docker:
      - image: azul/zulu-openjdk-alpine:8
    environment:
      BOOT_CLOJURE_VERSION: 1.8.0
  zulu7:
    <<: *shared
    docker:
      - image: azul/zulu-openjdk-alpine:7
  # "zulu9":
  #   docker:
  #     - image: debian/jessie-minimal
  #   working_directory: ~/repo
  #   environment:
  #     JVM_OPTS: -Xmx3200m
  #     BOOT_JAVA_COMMAND:
  #   steps:
  #     - checkout
  #     - run: .circleci/install_zulu9
  #     - run: .circleci/install_boot.sh
  #     - run: ./boot testing
  #     - run: ./boot test
  docs:
    docker:
      - image: azul/zulu-openjdk-debian:8
    steps:
      - checkout
      - run: .circleci/docs.sh
      - run: apt-get -y install curl build-essential git-core
      - run: curl -sL https://deb.nodesource.com/setup_6.x | bash -
      - run: apt-get install -y nodejs
      - run: .circleci/install_boot.sh
      - run: BOOT_JVM_OPTIONS=-Xmx3200m BOOT_AS_ROOT=yes ./boot testing
      - run: BOOT_JVM_OPTIONS=-Xmx3200m BOOT_AS_ROOT=yes ./boot codox target
      - run: mv -f target/doc/ ./
      - run: git checkout gh-pages
      - run: find . -mindepth 1 -maxdepth 1 -type f | xargs rm -f
      - run: mv -f doc/* .
      - run: rmdir doc
      - run: git add -A .
      - run: git commit -m "Rebuild website documentation"
      - run: git config user.name "CircleCI"
      - run: git config user.email "docs@circleci"
      - run: openssl aes-256-cbc -d -in docs_rsa.env -out $HOME/.ssh/docs_rsa -k $DOC_KEY_PASSWORD
      - run: git push origin gh-pages
workflows:
  version: 2
  build:
    jobs:
      - zulu8
      - zulu8_clojure1.8
      - zulu7
      - docs:
          requires:
            - zulu8
            - zulu8_clojure1.8
            - zulu7
    
